theme: jekyll-theme-minimal
title: [Chikako Takahashi]
description: [A short description of your site's purpose]
logo: [https://github.com/Chikako-Takahashi/Chikako-Takahashi.github.io.profilePic.png]
